# Generated by Django 5.1 on 2024-08-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='detail_short',
            field=models.TextField(max_length=255),
        ),
    ]
