# Generated by Django 5.1 on 2024-08-29 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0002_alter_service_detail_short'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmdservice',
            name='user',
        ),
        migrations.AddField(
            model_name='cmdservice',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
