# Generated by Django 5.1 on 2024-08-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0003_remove_cmdservice_user_cmdservice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
