# Generated by Django 5.1 on 2024-09-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0004_service_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisation',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
